#font
font_family JetBrainsMono Nerd Font
font_size 12.0

#window
background_opacity 0.85
confirm_os_window_close 0

#padding
window_padding_width 10

#cursor
cursor_shape beam
cursor_blink_interval 0.5
mouse_hide_wait -5.0
cursor_trail 40                          
cursor_trail_size 24
#cursor_trail_decay 0.1 0.4
cursor_trail_start_threshold 6
mouse_map right press ungrabbed paste_from_clipboard
copy_on_select yes

#performance
enable_audio_bell no

#theme colors
# foreground #cdd6f4
# foreground #1e1e2e
# selection_foreground #1e1e2e
# selection_foreground #f5e0dc

#url style
# url_color #89b4fa

#tabs
tab_bar_edge top
tab_bar_style powerline

#window blur (works with hyprland)
background_blur 8

#copy paste
copy_on_select yes
enable_audio_bell no

# BEGIN_KITTY_THEME
# Catppuccin-Mocha
include current-theme.conf
# END_KITTY_THEME
