label {
	text = $TIME
	font_size = 48
	position = 0, 80
	halign = center
	valign = center
}

background {
	blur_passes = 2
	blur_size = 8
}

input-field {
	size = 250, 50
	position = 0, -20
	dots_center = true
	fade_on_empty = false
}
